const actionTypes = {
    INITIALIZE_POSTS : "INITIALIZE_POSTS",
    INITIALIZE_USERS:"INITIALIZE_USERS",
    SET_LOADER:"SET_LOADER",
    SET_SEARCHEDUSER:"SET_SEARCHEDUSER",
    SET_THEME:"SET_THEME",
    SET_BOOKMARKS:"SET_BOOKMARKS",
    SET_SORT:"SET_SORT",
}



export default actionTypes
